namespace HypoxicTimer
{
    partial class DiaryForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DiaryForm));
            this.OkButton = new System.Windows.Forms.Button();
            this.DiaryPlotSurface2D = new NPlot.Windows.PlotSurface2D();
            this.DiaryDataGridView = new System.Windows.Forms.DataGridView();
            this.Date = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Comment = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.LHTi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.FHTI = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.HidenEntry = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.SpO2 = new DataGridViewSparklineColumn();
            this.HistogramPlotSurface2D = new NPlot.Windows.PlotSurface2D();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn5 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn6 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            ((System.ComponentModel.ISupportInitialize)(this.DiaryDataGridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.SuspendLayout();
            // 
            // OkButton
            // 
            this.OkButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.OkButton.Location = new System.Drawing.Point(13, 568);
            this.OkButton.Name = "OkButton";
            this.OkButton.Size = new System.Drawing.Size(75, 23);
            this.OkButton.TabIndex = 0;
            this.OkButton.Text = "OK";
            this.OkButton.UseVisualStyleBackColor = true;
            this.OkButton.Click += new System.EventHandler(this.OkButton_Click);
            // 
            // DiaryPlotSurface2D
            // 
            this.DiaryPlotSurface2D.AutoScaleAutoGeneratedAxes = false;
            this.DiaryPlotSurface2D.AutoScaleTitle = false;
            this.DiaryPlotSurface2D.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.DiaryPlotSurface2D.DateTimeToolTip = false;
            this.DiaryPlotSurface2D.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DiaryPlotSurface2D.Legend = null;
            this.DiaryPlotSurface2D.LegendZOrder = -1;
            this.DiaryPlotSurface2D.Location = new System.Drawing.Point(0, 0);
            this.DiaryPlotSurface2D.Name = "DiaryPlotSurface2D";
            this.DiaryPlotSurface2D.RightMenu = null;
            this.DiaryPlotSurface2D.ShowCoordinates = false;
            this.DiaryPlotSurface2D.Size = new System.Drawing.Size(619, 182);
            this.DiaryPlotSurface2D.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.DiaryPlotSurface2D.TabIndex = 1;
            this.DiaryPlotSurface2D.Text = "plotSurface2D1";
            this.DiaryPlotSurface2D.Title = "";
            this.DiaryPlotSurface2D.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.DiaryPlotSurface2D.XAxis1 = null;
            this.DiaryPlotSurface2D.XAxis2 = null;
            this.DiaryPlotSurface2D.YAxis1 = null;
            this.DiaryPlotSurface2D.YAxis2 = null;
            // 
            // DiaryDataGridView
            // 
            this.DiaryDataGridView.AllowUserToAddRows = false;
            this.DiaryDataGridView.AllowUserToDeleteRows = false;
            this.DiaryDataGridView.AllowUserToResizeRows = false;
            this.DiaryDataGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.DiaryDataGridView.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Date,
            this.Comment,
            this.LHTi,
            this.FHTI,
            this.HidenEntry,
            this.SpO2});
            this.DiaryDataGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DiaryDataGridView.Location = new System.Drawing.Point(0, 0);
            this.DiaryDataGridView.Name = "DiaryDataGridView";
            this.DiaryDataGridView.Size = new System.Drawing.Size(619, 160);
            this.DiaryDataGridView.TabIndex = 2;
            this.DiaryDataGridView.CellEndEdit += new System.Windows.Forms.DataGridViewCellEventHandler(this.DiaryDataGridView_CellEndEdit);
            this.DiaryDataGridView.RowEnter += new System.Windows.Forms.DataGridViewCellEventHandler(this.DiaryDataGridView_RowEnter);
            // 
            // Date
            // 
            this.Date.HeaderText = "Date";
            this.Date.Name = "Date";
            this.Date.ReadOnly = true;
            // 
            // Comment
            // 
            this.Comment.HeaderText = "Comment";
            this.Comment.Name = "Comment";
            // 
            // LHTi
            // 
            this.LHTi.HeaderText = "HTi";
            this.LHTi.Name = "LHTi";
            this.LHTi.ReadOnly = true;
            // 
            // FHTI
            // 
            this.FHTI.HeaderText = "Full HTi";
            this.FHTI.Name = "FHTI";
            this.FHTI.ReadOnly = true;
            // 
            // HidenEntry
            // 
            this.HidenEntry.HeaderText = "Hidden";
            this.HidenEntry.Name = "HidenEntry";
            this.HidenEntry.Visible = false;
            // 
            // SpO2Key
            // 
            this.SpO2.HeaderText = "SpO2";
            this.SpO2.Name = "SpO2";
            this.SpO2.ReadOnly = true;
            this.SpO2.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.SpO2.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            // 
            // HistogramPlotSurface2D
            // 
            this.HistogramPlotSurface2D.AutoScaleAutoGeneratedAxes = false;
            this.HistogramPlotSurface2D.AutoScaleTitle = false;
            this.HistogramPlotSurface2D.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.HistogramPlotSurface2D.DateTimeToolTip = false;
            this.HistogramPlotSurface2D.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HistogramPlotSurface2D.Legend = null;
            this.HistogramPlotSurface2D.LegendZOrder = -1;
            this.HistogramPlotSurface2D.Location = new System.Drawing.Point(0, 0);
            this.HistogramPlotSurface2D.Name = "HistogramPlotSurface2D";
            this.HistogramPlotSurface2D.RightMenu = null;
            this.HistogramPlotSurface2D.ShowCoordinates = false;
            this.HistogramPlotSurface2D.Size = new System.Drawing.Size(619, 209);
            this.HistogramPlotSurface2D.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.HistogramPlotSurface2D.TabIndex = 3;
            this.HistogramPlotSurface2D.Text = "plotSurface2D1";
            this.HistogramPlotSurface2D.Title = "";
            this.HistogramPlotSurface2D.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.HistogramPlotSurface2D.XAxis1 = null;
            this.HistogramPlotSurface2D.XAxis2 = null;
            this.HistogramPlotSurface2D.YAxis1 = null;
            this.HistogramPlotSurface2D.YAxis2 = null;
            // 
            // dataGridViewTextBoxColumn1
            // 
            this.dataGridViewTextBoxColumn1.HeaderText = "Date";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            // 
            // dataGridViewTextBoxColumn2
            // 
            this.dataGridViewTextBoxColumn2.HeaderText = "Comment";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            // 
            // dataGridViewTextBoxColumn3
            // 
            this.dataGridViewTextBoxColumn3.HeaderText = "HTi";
            this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
            this.dataGridViewTextBoxColumn3.ReadOnly = true;
            // 
            // dataGridViewTextBoxColumn4
            // 
            this.dataGridViewTextBoxColumn4.HeaderText = "Full HTi";
            this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
            this.dataGridViewTextBoxColumn4.ReadOnly = true;
            // 
            // dataGridViewTextBoxColumn5
            // 
            this.dataGridViewTextBoxColumn5.HeaderText = "Hidden";
            this.dataGridViewTextBoxColumn5.Name = "dataGridViewTextBoxColumn5";
            this.dataGridViewTextBoxColumn5.Visible = false;
            // 
            // dataGridViewTextBoxColumn6
            // 
            this.dataGridViewTextBoxColumn6.HeaderText = "SpO2";
            this.dataGridViewTextBoxColumn6.Name = "dataGridViewTextBoxColumn6";
            this.dataGridViewTextBoxColumn6.ReadOnly = true;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.splitContainer1.Location = new System.Drawing.Point(3, 3);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.splitContainer2);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.DiaryDataGridView);
            this.splitContainer1.Size = new System.Drawing.Size(619, 559);
            this.splitContainer1.SplitterDistance = 395;
            this.splitContainer1.TabIndex = 4;
            // 
            // splitContainer2
            // 
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.Location = new System.Drawing.Point(0, 0);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer2.Panel1
            // 
            this.splitContainer2.Panel1.Controls.Add(this.DiaryPlotSurface2D);
            // 
            // splitContainer2.Panel2
            // 
            this.splitContainer2.Panel2.Controls.Add(this.HistogramPlotSurface2D);
            this.splitContainer2.Size = new System.Drawing.Size(619, 395);
            this.splitContainer2.SplitterDistance = 182;
            this.splitContainer2.TabIndex = 0;
            // 
            // DiaryForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(622, 603);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.OkButton);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "DiaryForm";
            this.Text = "Diary";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.DiaryForm_FormClosing);
            ((System.ComponentModel.ISupportInitialize)(this.DiaryDataGridView)).EndInit();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
            this.splitContainer2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button OkButton;
        private NPlot.Windows.PlotSurface2D DiaryPlotSurface2D;
        private System.Windows.Forms.DataGridView DiaryDataGridView;
        private NPlot.Windows.PlotSurface2D HistogramPlotSurface2D;
        private System.Windows.Forms.DataGridViewTextBoxColumn Date;
        private System.Windows.Forms.DataGridViewTextBoxColumn Comment;
        private System.Windows.Forms.DataGridViewTextBoxColumn LHTi;
        private System.Windows.Forms.DataGridViewTextBoxColumn FHTI;
        private System.Windows.Forms.DataGridViewTextBoxColumn HidenEntry;
        private DataGridViewSparklineColumn SpO2;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn5;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn6;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.SplitContainer splitContainer2;
    }
}